### ISSUE TITLE
recolor the image

### ISSUE THREAD

**Issue by EricaQing** [JianchaoTan/fastLayerDecomposition#1]
How can I recolor the image by edit the palette color?

**Comment by JianchaoTan** [comment]
Users can perform global recoloring in our web GUI: https://yig.github.io/image-rgb-in-3D/ 
First load the original image, then drag-and-drop the palette .js file, and finally drag-and-drop the mixing weights .js file. Then you can click and move the palette vertices in GUI to do global recoloring. 
This recoloring GUI is used in our previous project: https://github.com/JianchaoTan/Decompose-Single-Image-Into-Layers
